services:
  # Django API Service
  - type: web
    name: resume-parser-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn resume_parser.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://pdf-parser-eight.vercel.app"
      - key: HUGGINGFACE_API_URL
        sync: false
      - key: HUGGINGFACE_API_TOKEN
        sync: false 